config/routes.rb
Rails.application.routes.draw do
	post 'games/login', to: "games#login", as: "new_game"

  post 'deck/:deck_id/start_game', to: 'games#start_game', as: 'start'

  post 'question/receive_answer', to: 'games#receive_answer', as: 'receive'

  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deck.rb
class Deck < ApplicationRecord
	has_many :games
	has_many :questions
	has_many :users, :through => :games
end

app/models/game.rb
class Game < ApplicationRecord
	belongs_to :user
	belongs_to :deck
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :deck
	has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
	has_many :games
	has_many :decks, :through => :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def login
  	p 'Hola'
  	p @games_email = params[:email]
  	p @games_password = params[:password]
  	authentification(@games_email, @games_password)
  end

  def menu_game
    p '******************************************'
    p session[:user_id]
    p '******************************************'
  	p @show_decks = Deck.all
  	p 'Este es el valor que recibe del usuario'
  	
  end

  def start_game
  	p 'Este es el objeto del deck que se tomara el valor para dirigir al metodo'
  	p @user_deck = params[:deck_id]
  	p 'Este es el arreglo de questions'
  	p @find_deck = Deck.find(@user_deck).questions
  	p 'Estos son los id'
  end

  def receive_answer
    @count_good = 0
    @count_bad = 0
    @answer_value = []
  	p 'Estas adentro de receive_answer'
  	p @answer = params
    @answer.each do |evaluation, value|
      if evaluation.to_i != 0
        @answer_value << value
      end
    end
    @answer_value.each do |finding|
      @status = Answer.find_by(answer: finding)
      p @status.status
      if @status.status == true 
        @count_good += 1
      else
        @count_bad += 1
      end
    end
    p @count_good
    p @count_bad
    @current = session[:user_id]
    @user_score = Game.create(user_id: @current, deck_id: @find_deck, score: @count_good)
    p @all_scores = Game.all
  end

  private
  def authentification(email, password)
    p 'Estas en authentification'
    p @finder = User.find_by(email: email, password: password)
    if @finder
      session[:user_id] = @finder.id
      p '******************************************'
      p @finder      
      p '******************************************'
      menu_game
      render 'menu_game'
    else
      redirect_to create
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/index.html.erb
<h1>Bienvenido a Maraton!!!</h1>
<p>Este es un juego de contestar preguntas</p>

<%= form_tag new_game_path do %>
  <p>
  	Ingresa tu email y password:<br>
  	<%= label_tag :email %><br>
    <%= text_field_tag :email %>
  </p>

  <p>
  	<%= label_tag :password %><br>
    <%= text_field_tag :password %>
  </p>	
 
  <p>
    <%= submit_tag "Submit" %>
  </p>
<% end %>

app/views/games/menu_game.html.erb
<h1>Bienvenido!!!</h1>
<p>Escoga el Deck con el cual quiere jugar</p>

<ul>
	<% @show_decks.each do |deck|%>
		<li>
			<div><%= button_to deck.name, start_path(deck), :method => "post" %></div>
		<li>
	<% end %>
</ul>

app/views/games/receive_answer.html.erb
<h1>Bienvenido a los Resultados!!!</h1>
<p>Aqui se encuentran todos los resultados!!!</p>

<table>
  <tr>
    <th>Scores</th>
  </tr>
    <% @all_scores.each do |show| %>
     	<tr>
     		<td><%= show.user_id %></td>
     	</tr>
      <tr>
      	<td><%= show.deck_id %></td>
      </tr>
      <tr>
      	<td><%= show.score %></td>
      </tr>
  <% end %>
</table>

app/views/games/start_game.html.erb
<h1>Bienvenido a tu Deck!!!</h1>
<p>Seleccione las preguntas correctas</p>

<!-- mostrar formulario -->
<%= form_tag ("/question/receive_answer") %>
  <table>
    <tr>
      <th>Preguntas</th>
    </tr>
    <% @find_deck.each do |question| %>
     	<tr>
     		<td><%= question.question %></td>
     	</tr>
      <tr>
      	<td>
        	<% question.answers.each do |option| %>
          <%= radio_button_tag question.id, option.answer, option_id: option.id, answer: option.answer %><%= option.answer %>   
          <%end%>
        <br>
      	</td>
      </tr>
    <% end %>
 	</table>
<%= submit_tag ("Submit") %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maraton</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>